-- ai-goofish-monitor 业务表（与 SQLite schema 对齐）
-- 在 Supabase SQL Editor 执行，或通过 supabase db push / migration 应用
-- Project: wkhatdhgohkpsqkytotz

-- 可选：业务专用 schema，减少与 Supabase 默认 public API 暴露面
-- CREATE SCHEMA IF NOT EXISTS goofish;

CREATE TABLE IF NOT EXISTS app_metadata (
    key TEXT PRIMARY KEY,
    value TEXT NOT NULL
);

CREATE TABLE IF NOT EXISTS tasks (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    task_name TEXT NOT NULL,
    enabled BOOLEAN NOT NULL DEFAULT TRUE,
    keyword TEXT NOT NULL,
    description TEXT,
    analyze_images BOOLEAN NOT NULL DEFAULT TRUE,
    max_pages INTEGER NOT NULL DEFAULT 3,
    personal_only BOOLEAN NOT NULL DEFAULT TRUE,
    min_price TEXT,
    max_price TEXT,
    cron TEXT,
    ai_prompt_base_file TEXT NOT NULL DEFAULT 'prompts/base_prompt.txt',
    ai_prompt_criteria_file TEXT NOT NULL DEFAULT '',
    account_state_file TEXT,
    account_strategy TEXT NOT NULL DEFAULT 'auto',
    free_shipping BOOLEAN NOT NULL DEFAULT TRUE,
    new_publish_option TEXT,
    region TEXT,
    decision_mode TEXT NOT NULL DEFAULT 'ai',
    keyword_rules_json JSONB NOT NULL DEFAULT '[]'::jsonb,
    is_running BOOLEAN NOT NULL DEFAULT FALSE
);

CREATE TABLE IF NOT EXISTS result_items (
    id BIGSERIAL PRIMARY KEY,
    result_filename TEXT NOT NULL,
    keyword TEXT NOT NULL,
    task_name TEXT NOT NULL,
    crawl_time TEXT NOT NULL,
    publish_time TEXT,
    price DOUBLE PRECISION,
    price_display TEXT,
    item_id TEXT,
    title TEXT,
    link TEXT,
    link_unique_key TEXT NOT NULL,
    seller_nickname TEXT,
    is_recommended BOOLEAN NOT NULL DEFAULT FALSE,
    analysis_source TEXT,
    keyword_hit_count INTEGER NOT NULL DEFAULT 0,
    status TEXT NOT NULL DEFAULT 'active',
    raw_json JSONB NOT NULL,
    CONSTRAINT uq_result_items_filename_link UNIQUE (result_filename, link_unique_key)
);

CREATE TABLE IF NOT EXISTS price_snapshots (
    id BIGSERIAL PRIMARY KEY,
    keyword_slug TEXT NOT NULL,
    keyword TEXT NOT NULL,
    task_name TEXT NOT NULL,
    snapshot_time TEXT NOT NULL,
    snapshot_day TEXT NOT NULL,
    run_id TEXT NOT NULL,
    item_id TEXT NOT NULL,
    title TEXT,
    price DOUBLE PRECISION NOT NULL,
    price_display TEXT,
    tags_json JSONB NOT NULL DEFAULT '[]'::jsonb,
    region TEXT,
    seller TEXT,
    publish_time TEXT,
    link TEXT,
    CONSTRAINT uq_price_snapshots_run_item UNIQUE (keyword_slug, run_id, item_id)
);

CREATE TABLE IF NOT EXISTS result_blacklist_rules (
    result_filename TEXT PRIMARY KEY,
    blacklist_keywords_json JSONB NOT NULL DEFAULT '[]'::jsonb,
    updated_at TEXT NOT NULL
);

CREATE TABLE IF NOT EXISTS collected_items (
    id BIGSERIAL PRIMARY KEY,
    result_item_id BIGINT NOT NULL UNIQUE REFERENCES result_items(id) ON DELETE CASCADE,
    collected_at TEXT NOT NULL,
    sku_fetch_status TEXT NOT NULL DEFAULT 'pending',
    sku_fetched_at TEXT,
    sku_json JSONB,
    sku_error TEXT
);

CREATE INDEX IF NOT EXISTS idx_tasks_name ON tasks(task_name);
CREATE INDEX IF NOT EXISTS idx_results_filename_crawl ON result_items(result_filename, crawl_time DESC);
CREATE INDEX IF NOT EXISTS idx_results_filename_publish ON result_items(result_filename, publish_time DESC);
CREATE INDEX IF NOT EXISTS idx_results_filename_price ON result_items(result_filename, price DESC);
CREATE INDEX IF NOT EXISTS idx_results_filename_recommended ON result_items(result_filename, is_recommended, analysis_source, crawl_time DESC);
CREATE INDEX IF NOT EXISTS idx_results_filename_status_crawl ON result_items(result_filename, status, crawl_time DESC);
CREATE INDEX IF NOT EXISTS idx_snapshots_keyword_time ON price_snapshots(keyword_slug, snapshot_time DESC);
CREATE INDEX IF NOT EXISTS idx_snapshots_keyword_item_time ON price_snapshots(keyword_slug, item_id, snapshot_time DESC);
CREATE INDEX IF NOT EXISTS idx_collected_items_collected_at ON collected_items(collected_at DESC);

-- RLS：阻止 PostgREST/Data API 匿名访问；后端用 Database 连接串（postgres 角色）不受此限制
ALTER TABLE app_metadata ENABLE ROW LEVEL SECURITY;
ALTER TABLE tasks ENABLE ROW LEVEL SECURITY;
ALTER TABLE result_items ENABLE ROW LEVEL SECURITY;
ALTER TABLE price_snapshots ENABLE ROW LEVEL SECURITY;
ALTER TABLE result_blacklist_rules ENABLE ROW LEVEL SECURITY;
ALTER TABLE collected_items ENABLE ROW LEVEL SECURITY;

-- 不对 anon / authenticated 开放策略 = API 侧默认拒绝（仅服务端直连可读写）

COMMENT ON TABLE tasks IS '闲鱼监控任务配置';
COMMENT ON TABLE result_items IS '爬取结果主表';
